-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.email_validation
(
    id integer NOT NULL,
    user_id integer NOT NULL,
    is_valid boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers
(
    user_id integer NOT NULL,
    company_name character varying(50) NOT NULL,
    web_address character varying NOT NULL,
    phone_number character varying NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.job_positions
(
    id integer NOT NULL,
    position_name character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_seekers
(
    user_id integer NOT NULL,
    first_name character varying(20) NOT NULL,
    last_name character varying(20) NOT NULL,
    national_id character varying(11) NOT NULL,
    birth_year date NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.job_seekers_positions
(
    id integer NOT NULL,
    job_seeker_id integer NOT NULL,
    job_position_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.staff_validation
(
    id integer NOT NULL,
    employer_id integer NOT NULL,
    is_valid boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    user_id integer NOT NULL,
    email character varying(50) NOT NULL,
    password character varying(50) NOT NULL,
    PRIMARY KEY (user_id)
);

ALTER TABLE public.email_validation
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;


ALTER TABLE public.job_seekers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;


ALTER TABLE public.job_seekers_positions
    ADD FOREIGN KEY (job_position_id)
    REFERENCES public.job_positions (id)
    NOT VALID;


ALTER TABLE public.job_seekers_positions
    ADD FOREIGN KEY (job_seeker_id)
    REFERENCES public.job_seekers (user_id)
    NOT VALID;


ALTER TABLE public.staff_validation
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (user_id)
    NOT VALID;

END;